export const SITE_NAME = "Teklin";
export const SITE_URL = "https://teklin.in";
export const SITE_DESCRIPTION =
  "Teklin is a full-spectrum software development company. We design, build, and scale digital products that users love and businesses depend on.";
export const SITE_EMAIL = "contact@teklin.in";
export const SITE_TWITTER = "@teklin_in";
export const SITE_PHONE = "+91 9707276661";
export const SITE_ADDRESS = "Kanishail, Sribhumi (Karimganj), Assam, India 788727";
export const SITE_HOURS = "Monday–Saturday, 9:00 AM – 6:00 PM IST";
export const SOCIAL_LINKS = {
  facebook: "https://facebook.com/profile.php?id=61571269328546",
  instagram: "https://instagram.com/teklin.in",
  twitter: "https://x.com/Teklin_in",
  linkedin: "https://linkedin.com/company/teklin/",
};

export const NAV_LINKS = [
  { label: "Services", href: "/services" },
  { label: "Work", href: "/work" },
  { label: "About", href: "/about" },
  { label: "Process", href: "/process" },
  { label: "Insights", href: "/insights" },
  { label: "Careers", href: "/careers" },
  { label: "Estimate", href: "/estimate" },
];

export const SERVICES = [
  {
    slug: "custom-software-development",
    title: "Custom Software Development",
    shortTitle: "Custom Software",
    description:
      "Bespoke software solutions engineered to your exact requirements — from greenfield builds to legacy modernisation.",
    icon: "Code2",
    featured: true,
    colSpan: 2,
  },
  {
    slug: "web-development",
    title: "Web Development",
    shortTitle: "Web Dev",
    description:
      "React, Next.js, and full-stack web applications that are fast, accessible, and built to scale.",
    icon: "Globe",
    featured: false,
    colSpan: 1,
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development",
    shortTitle: "Mobile Apps",
    description:
      "Native and cross-platform iOS & Android apps your users will actually want to open.",
    icon: "Smartphone",
    featured: false,
    colSpan: 1,
  },
  {
    slug: "ai-machine-learning",
    title: "AI & Machine Learning",
    shortTitle: "AI & ML",
    description:
      "Intelligent systems, LLM integrations, and ML pipelines that give your product a competitive edge.",
    icon: "Brain",
    featured: false,
    colSpan: 1,
  },
  {
    slug: "saas-product-development",
    title: "SaaS Product Development",
    shortTitle: "SaaS Products",
    description:
      "End-to-end SaaS products — architecture, multi-tenancy, billing, onboarding, and beyond.",
    icon: "Layers",
    featured: true,
    colSpan: 2,
  },
  {
    slug: "cloud-devops",
    title: "Cloud Infrastructure & DevOps",
    shortTitle: "Cloud & DevOps",
    description:
      "AWS, GCP, and Azure infrastructure with CI/CD pipelines, observability, and zero-downtime deployments.",
    icon: "Cloud",
    featured: false,
    colSpan: 1,
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX Design",
    shortTitle: "Design",
    description:
      "User research, interaction design, and design systems that delight users and drive conversion.",
    icon: "Pen",
    featured: false,
    colSpan: 1,
  },
  {
    slug: "enterprise-software",
    title: "Enterprise Software",
    shortTitle: "Enterprise",
    description:
      "Scalable, secure enterprise platforms built for complex organisations.",
    icon: "Building2",
    featured: false,
    colSpan: 1,
  },
  {
    slug: "digital-transformation",
    title: "Digital Transformation",
    shortTitle: "Transformation",
    description:
      "Strategy and execution for modernising legacy systems and processes.",
    icon: "Zap",
    featured: false,
    colSpan: 1,
  },
  { slug: "mvp-development", title: "MVP Development", shortTitle: "MVP", description: "From founder idea to market-ready product in 6–10 weeks. Lean, validated, and built to scale.", icon: "Rocket", featured: false, colSpan: 1 },
  { slug: "fintech-software", title: "FinTech Software", shortTitle: "FinTech", description: "Secure transaction flows, payment integrations, and role-based financial workflows.", icon: "CreditCard", featured: false, colSpan: 1 },
  { slug: "healthcare-software", title: "Healthcare Software", shortTitle: "Healthcare", description: "Patient management, teleconsultation, scheduling, and HIPAA-conscious product architecture.", icon: "Heart", featured: false, colSpan: 1 },
  { slug: "ecommerce-development", title: "E-commerce Development", shortTitle: "E-commerce", description: "Conversion-first storefronts, catalog management, and seamless checkout experiences.", icon: "ShoppingCart", featured: false, colSpan: 1 },
  { slug: "legacy-modernization", title: "Legacy Modernisation", shortTitle: "Modernisation", description: "Migrate and modernise aging systems without disrupting business continuity.", icon: "RefreshCw", featured: false, colSpan: 1 },
  { slug: "dedicated-teams", title: "Dedicated Development Teams", shortTitle: "Dedicated Teams", description: "Flexible, sprint-managed teams of developers, designers, and QA that scale with your roadmap.", icon: "Users", featured: false, colSpan: 1 },
  { slug: "software-testing", title: "Software Testing & QA", shortTitle: "QA & Testing", description: "Automated and manual testing strategies that ensure production-grade reliability.", icon: "ShieldCheck", featured: false, colSpan: 1 },
  { slug: "product-discovery", title: "Product Discovery Workshop", shortTitle: "Discovery", description: "3–10 day workshops that define scope, validate assumptions, and produce an actionable roadmap.", icon: "Search", featured: false, colSpan: 1 },
  { slug: "edtech-software", title: "EdTech Software", shortTitle: "EdTech", description: "Learning platforms, assessment tools, and cohort analytics built for engagement and retention.", icon: "BookOpen", featured: false, colSpan: 1 },
  { slug: "logistics-software", title: "Logistics Software", shortTitle: "Logistics", description: "Fleet management, dispatch consoles, real-time tracking, and proof-of-delivery systems.", icon: "Truck", featured: false, colSpan: 1 },
  { slug: "real-estate-software", title: "Real Estate Software", shortTitle: "Real Estate", description: "Property search, agent CRM, listing sync, and lead routing for modern property businesses.", icon: "Building", featured: false, colSpan: 1 },
  { slug: "graphic-design", title: "Graphic Design", shortTitle: "Design", description: "Brand identity, UI assets, and visual communication that makes your product memorable.", icon: "Palette", featured: false, colSpan: 1 },
];

export const STATS = [
  { value: 240, suffix: "+", label: "Businesses Served" },
  { value: 99.99, suffix: "%", label: "Uptime Achieved" },
  { value: 60, suffix: "%", label: "Avg Latency Reduction" },
  { value: 98, suffix: "%", label: "On-Time Delivery" },
];

export const TECH_STACK = {
  Frontend: ["React", "Next.js", "TypeScript", "Vue", "Angular", "Svelte"],
  Backend: ["Node.js", "Python", "Go", "Rust", "Java", ".NET"],
  Mobile: ["React Native", "Flutter", "Swift", "Kotlin"],
  Cloud: ["AWS", "GCP", "Azure", "Vercel", "Docker", "Kubernetes"],
  Database: ["PostgreSQL", "MongoDB", "Redis", "Supabase"],
  "AI/ML": ["TensorFlow", "PyTorch", "OpenAI", "LangChain", "Hugging Face"],
};

export const PROCESS_STEPS = [
  {
    number: "01",
    title: "Discovery & Strategy",
    description:
      "We dive deep into your business, users, and market to understand the real problem before writing a single line of code.",
    icon: "Search",
  },
  {
    number: "02",
    title: "Architecture & Design",
    description:
      "Wireframes, interactive prototypes, and design systems that set the technical foundation for everything that follows.",
    icon: "Layout",
  },
  {
    number: "03",
    title: "Agile Development",
    description:
      "Sprint-based development with continuous delivery. You see progress every two weeks — not just at the end.",
    icon: "Code2",
  },
  {
    number: "04",
    title: "Quality Assurance",
    description:
      "Automated testing, thorough code review, and performance audits ensure what ships is production-grade.",
    icon: "ShieldCheck",
  },
  {
    number: "05",
    title: "Launch & Deploy",
    description:
      "Zero-downtime deployment with full monitoring, alerting, and rollback capabilities from day one.",
    icon: "Rocket",
  },
  {
    number: "06",
    title: "Scale & Optimise",
    description:
      "Post-launch performance tuning, feature iteration, and scaling infrastructure as your user base grows.",
    icon: "TrendingUp",
  },
];

export const TESTIMONIALS = [
  {
    quote:
      "Teklin transformed our legacy platform into a modern SaaS product that our customers love. The team's technical depth and communication were outstanding throughout.",
    author: "Sarah Chen",
    role: "CTO",
    company: "Finvest Labs",
    avatar: "SC",
  },
  {
    quote:
      "We went from idea to a live product in 12 weeks. The quality of code and the design exceeded everything we expected from an external team.",
    author: "Marcus Williams",
    role: "Founder & CEO",
    company: "Orbita Health",
    avatar: "MW",
  },
  {
    quote:
      "The AI integration they built for our platform resulted in a 340% increase in user engagement. These engineers truly understand the product side of things.",
    author: "Priya Nair",
    role: "Head of Product",
    company: "DataStream Inc.",
    avatar: "PN",
  },
  {
    quote:
      "Professional, proactive, and they actually care about the outcome. Teklin feels like an extension of our team, not just a vendor.",
    author: "James O'Brien",
    role: "VP Engineering",
    company: "Nexora Retail",
    avatar: "JO",
  },
  {
    quote:
      "Their DevOps team cut our deployment time from 3 hours to 8 minutes and reduced incidents by 70%. Game-changing work.",
    author: "Anika Müller",
    role: "Engineering Manager",
    company: "LogiCore GmbH",
    avatar: "AM",
  },
];

export const CASE_STUDIES = [
  {
    slug: "finvest-labs",
    title: "Finvest Labs",
    subtitle: "SaaS Platform Modernisation",
    industry: "FinTech",
    year: "2024",
    category: "SaaS",
    description:
      "Rebuilt a 10-year-old legacy trading platform into a real-time SaaS product serving 15,000+ traders.",
    problem:
      "A legacy monolith was slowing releases, increasing incidents, and limiting onboarding flows.",
    approach:
      "We ran discovery, mapped workflows, migrated in phases, and shipped a new UI with a modern API layer.",
    solution:
      "A multi-tenant SaaS with real-time trading views, role-based access, and an audited reporting pipeline.",
    duration: "12 weeks",
    services: ["Product discovery", "UI/UX", "Full-stack engineering", "DevOps"],
    deliverables: [
      "Design system + components",
      "New customer onboarding",
      "Admin console and reporting",
      "CI/CD + monitoring",
    ],
    features: [
      "Real-time dashboards",
      "Role-based access control",
      "Automated reporting exports",
      "Audit trails",
    ],
    results: [
      { metric: "↑ 340%", label: "Conversion rate" },
      { metric: "-62%", label: "Support tickets" },
      { metric: "99.95%", label: "Uptime" },
      { metric: "2.3s", label: "Avg. load" },
    ],
    metric: "↑ 340% conversion rate",
    image: "/images/work/finvest.svg",
    tags: ["Next.js", "Go", "PostgreSQL", "AWS"],
    color: "#8B5CF6",
  },
  {
    slug: "orbita-health",
    title: "Orbita Health",
    subtitle: "AI-Powered Patient Platform",
    industry: "HealthTech",
    year: "2024",
    category: "AI/ML",
    description:
      "End-to-end patient management platform with ML-driven appointment optimisation and HIPAA compliance.",
    problem:
      "Care teams were juggling spreadsheets and disconnected tools, causing delays and missed follow-ups.",
    approach:
      "We designed patient journeys, built an API-first platform, and added ML scheduling with human override.",
    solution:
      "A secure patient platform with scheduling intelligence, communication workflows, and clinician dashboards.",
    duration: "10 weeks",
    services: ["Product design", "Mobile + web", "ML integration", "Compliance hardening"],
    deliverables: [
      "Clinician dashboard",
      "Patient portal",
      "Scheduling engine",
      "Audit logging",
    ],
    features: [
      "Smart appointment slots",
      "Automated reminders",
      "Care-plan tracking",
      "Secure messaging",
    ],
    results: [
      { metric: "-60%", label: "Scheduling time" },
      { metric: "+28%", label: "Show-up rate" },
      { metric: "99.9%", label: "Uptime" },
      { metric: "1.9s", label: "Portal load" },
    ],
    metric: "60% faster appointments",
    image: "/images/work/orbita.svg",
    tags: ["React Native", "Python", "FastAPI", "GCP"],
    color: "#06B6D4",
  },
  {
    slug: "datastream",
    title: "DataStream Inc.",
    subtitle: "Real-Time Analytics Dashboard",
    industry: "Data & Analytics",
    year: "2023",
    category: "Enterprise",
    description:
      "High-performance analytics platform processing 50M events per day with sub-second query times.",
    problem:
      "Decision-makers lacked trustworthy, near-real-time reporting and teams were blocked by slow queries.",
    approach:
      "We redesigned the data model, introduced streaming ingestion, and optimized query paths end-to-end.",
    solution:
      "A real-time analytics suite with multi-workspace dashboards, fast exploration, and alerting.",
    duration: "14 weeks",
    services: ["Data architecture", "Dashboard UI", "Performance engineering", "Cloud ops"],
    deliverables: [
      "Ingestion pipeline",
      "Dashboards + alerts",
      "Access controls",
      "Observability and SLOs",
    ],
    features: [
      "Sub-second exploration",
      "Saved queries",
      "Alert rules",
      "Usage analytics",
    ],
    results: [
      { metric: "50M", label: "Events/day" },
      { metric: "<900ms", label: "Query p95" },
      { metric: "-41%", label: "Infra cost" },
      { metric: "+3.4x", label: "Analyst throughput" },
    ],
    metric: "50M events/day",
    image: "/images/work/datastream.svg",
    tags: ["React", "Rust", "ClickHouse", "Kubernetes"],
    color: "#10B981",
  },

  // Additional projects (varied fields)
  {
    slug: "nexora-retail",
    title: "Nexora Retail",
    subtitle: "Headless Commerce Rebuild",
    industry: "Retail & E-commerce",
    year: "2025",
    category: "Web",
    description:
      "A headless storefront and admin suite built for high-traffic seasonal spikes and rapid merchandising updates.",
    problem: "A rigid storefront made promotions slow to launch and checkout performance inconsistent.",
    approach: "We split storefront from backend, optimized Core Web Vitals, and hardened checkout flows.",
    solution: "A fast, headless commerce experience with flexible CMS-driven landing pages.",
    duration: "8 weeks",
    services: ["Frontend engineering", "Backend integration", "Performance"],
    deliverables: ["Headless storefront", "Checkout revamp", "Promo templates"],
    features: ["Fast category pages", "Smart search", "Cart recovery"],
    results: [
      { metric: "+22%", label: "Revenue/visit" },
      { metric: "1.6s", label: "LCP" },
      { metric: "-35%", label: "Checkout drop-off" },
      { metric: "+18%", label: "Repeat purchase" },
    ],
    metric: "↓ 35% checkout drop-off",
    image: "/images/work/finvest.svg",
    tags: ["Next.js", "Node.js", "Stripe", "PostgreSQL"],
    color: "#8B5CF6",
  },
  {
    slug: "logicore-ops",
    title: "LogiCore",
    subtitle: "Fleet & Dispatch Operations",
    industry: "Logistics",
    year: "2025",
    category: "Enterprise",
    description:
      "An operations platform for dispatch, live tracking, proof-of-delivery, and performance reporting.",
    problem: "Dispatch teams relied on manual calls and fragmented tracking data.",
    approach: "We unified tracking, built operator workflows, and shipped incremental modules per depot.",
    solution: "A dispatch console with tracking, routing, and automated incident handling.",
    duration: "16 weeks",
    services: ["Platform engineering", "Integrations", "DevOps"],
    deliverables: ["Dispatch console", "Driver app", "Reporting"],
    features: ["Route planning", "Live ETAs", "PoD capture"],
    results: [
      { metric: "-48%", label: "Manual calls" },
      { metric: "+19%", label: "On-time rate" },
      { metric: "-31%", label: "Ops overhead" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "↑ 19% on-time delivery",
    image: "/images/work/datastream.svg",
    tags: ["Next.js", "Go", "PostGIS", "AWS"],
    color: "#10B981",
  },
  {
    slug: "edupulse",
    title: "EduPulse",
    subtitle: "Learning Platform + Mobile",
    industry: "EdTech",
    year: "2025",
    category: "Mobile",
    description:
      "A mobile-first learning platform with offline support, assessments, and cohort analytics.",
    problem: "Learners in low-connectivity regions struggled with drop-offs and incomplete coursework.",
    approach: "We designed offline-first flows and optimized media delivery and assessment syncing.",
    solution: "A mobile learning app with offline lessons, quizzes, and teacher dashboards.",
    duration: "10 weeks",
    services: ["Mobile engineering", "UX", "Backend"],
    deliverables: ["iOS/Android app", "Teacher dashboard", "Analytics"],
    features: ["Offline downloads", "Cohorts", "Quizzes"],
    results: [
      { metric: "+44%", label: "Course completion" },
      { metric: "-29%", label: "Churn" },
      { metric: "<2s", label: "Screen load" },
      { metric: "4.8★", label: "App rating" },
    ],
    metric: "↑ 44% completion",
    image: "/images/work/orbita.svg",
    tags: ["React Native", "Node.js", "PostgreSQL"],
    color: "#06B6D4",
  },
  {
    slug: "securepay",
    title: "SecurePay",
    subtitle: "Payments Risk Engine",
    industry: "FinTech",
    year: "2024",
    category: "AI/ML",
    description:
      "Fraud and risk scoring engine with real-time rules, alerts, and case management.",
    problem: "Chargebacks were rising and manual reviews could not keep up with transaction volume.",
    approach: "We combined rules + ML scoring, built explainability, and streamlined investigator workflows.",
    solution: "A risk platform with scoring, case queues, and real-time alerting.",
    duration: "12 weeks",
    services: ["ML integration", "Backend", "Dashboards"],
    deliverables: ["Risk scoring", "Case management", "Alerting"],
    features: ["Rules editor", "Explainable scores", "Queue management"],
    results: [
      { metric: "-52%", label: "Chargebacks" },
      { metric: "+2.6x", label: "Review capacity" },
      { metric: "<200ms", label: "Score latency" },
      { metric: "99.99%", label: "Availability" },
    ],
    metric: "↓ 52% chargebacks",
    image: "/images/work/finvest.svg",
    tags: ["Python", "FastAPI", "Kafka", "PostgreSQL"],
    color: "#F59E0B",
  },
  {
    slug: "homewise",
    title: "Homewise",
    subtitle: "Property Search & CRM",
    industry: "PropTech",
    year: "2024",
    category: "Web",
    description:
      "A property search experience with agent CRM, lead routing, and automated listings sync.",
    problem: "Leads were lost between portals and agents, and listing updates were inconsistent.",
    approach: "We centralized listings, built CRM pipelines, and added automation for lead routing.",
    solution: "A unified property search + CRM with fast filters and lead intelligence.",
    duration: "9 weeks",
    services: ["Web app", "Integrations", "Automation"],
    deliverables: ["Search UI", "Agent CRM", "Listing sync"],
    features: ["Map search", "Saved searches", "Lead scoring"],
    results: [
      { metric: "+31%", label: "Qualified leads" },
      { metric: "-70%", label: "Manual updates" },
      { metric: "1.7s", label: "LCP" },
      { metric: "+24%", label: "Agent productivity" },
    ],
    metric: "↑ 31% qualified leads",
    image: "/images/work/finvest.svg",
    tags: ["Next.js", "Node.js", "PostgreSQL"],
    color: "#8B5CF6",
  },
  {
    slug: "aeroroute",
    title: "AeroRoute",
    subtitle: "Travel Booking Platform",
    industry: "Travel",
    year: "2023",
    category: "SaaS",
    description:
      "A booking and itinerary platform with supplier integrations and customer self-serve changes.",
    problem: "Agents were overloaded with itinerary changes and supplier reconciliation.",
    approach: "We automated supplier sync and built self-serve change workflows with guardrails.",
    solution: "A booking SaaS with fast search, itinerary management, and support tooling.",
    duration: "11 weeks",
    services: ["Platform build", "Integrations", "UX"],
    deliverables: ["Search", "Itineraries", "Support console"],
    features: ["Supplier sync", "Self-serve changes", "Refund flows"],
    results: [
      { metric: "-38%", label: "Support load" },
      { metric: "+17%", label: "Conversion" },
      { metric: "99.9%", label: "Uptime" },
      { metric: "<2s", label: "Search p95" },
    ],
    metric: "↓ 38% support load",
    image: "/images/work/datastream.svg",
    tags: ["Next.js", "Go", "Redis", "AWS"],
    color: "#10B981",
  },
  {
    slug: "clinicflow",
    title: "ClinicFlow",
    subtitle: "Clinic Operations Suite",
    industry: "Healthcare",
    year: "2023",
    category: "Enterprise",
    description:
      "An internal operations suite for clinics: inventory, billing, scheduling, and reporting.",
    problem: "Multi-location clinics lacked consistent workflows and visibility across departments.",
    approach: "We standardized workflows and shipped modules incrementally with strict access controls.",
    solution: "A modular operations suite with RBAC, approvals, and detailed reporting.",
    duration: "15 weeks",
    services: ["Workflow design", "Engineering", "QA"],
    deliverables: ["Scheduling", "Billing", "Inventory"],
    features: ["Approvals", "Audit logs", "Reports"],
    results: [
      { metric: "-42%", label: "Admin time" },
      { metric: "+23%", label: "Billing accuracy" },
      { metric: "99.9%", label: "Uptime" },
      { metric: "-18%", label: "Stockouts" },
    ],
    metric: "↓ 42% admin time",
    image: "/images/work/orbita.svg",
    tags: ["Next.js", "Node.js", "PostgreSQL"],
    color: "#06B6D4",
  },
  {
    slug: "greengrid",
    title: "GreenGrid",
    subtitle: "Energy Monitoring Dashboard",
    industry: "ClimateTech",
    year: "2024",
    category: "Web",
    description:
      "A dashboard for facility-level energy monitoring, anomaly detection, and savings reporting.",
    problem: "Energy data was noisy and insights were delayed, limiting optimization decisions.",
    approach: "We built a unified data model and shipped anomaly detection + clear reporting.",
    solution: "A monitoring UI with alerts, benchmarking, and savings projections.",
    duration: "7 weeks",
    services: ["Dashboard UI", "Data integration", "Analytics"],
    deliverables: ["Energy dashboards", "Alerting", "Reports"],
    features: ["Benchmarking", "Alerts", "Exports"],
    results: [
      { metric: "-12%", label: "Energy spend" },
      { metric: "<1s", label: "Dash load" },
      { metric: "+3x", label: "Issue detection" },
      { metric: "-28%", label: "Manual reporting" },
    ],
    metric: "↓ 12% energy spend",
    image: "/images/work/datastream.svg",
    tags: ["React", "Node.js", "PostgreSQL"],
    color: "#10B981",
  },
  {
    slug: "hr-navigator",
    title: "HR Navigator",
    subtitle: "Hiring & Onboarding",
    industry: "HRTech",
    year: "2025",
    category: "SaaS",
    description:
      "Applicant tracking and onboarding automation for distributed teams.",
    problem: "Hiring pipelines were scattered across email and spreadsheets, slowing time-to-hire.",
    approach: "We streamlined pipeline stages and introduced templates, automation, and analytics.",
    solution: "An ATS + onboarding platform with approvals, checklists, and analytics.",
    duration: "9 weeks",
    services: ["SaaS build", "UX", "Automation"],
    deliverables: ["ATS", "Onboarding", "Templates"],
    features: ["Stage automation", "Offer workflows", "Analytics"],
    results: [
      { metric: "-26%", label: "Time-to-hire" },
      { metric: "+19%", label: "Offer accept" },
      { metric: "99.9%", label: "Uptime" },
      { metric: "+2.1x", label: "Recruiter capacity" },
    ],
    metric: "↓ 26% time-to-hire",
    image: "/images/work/finvest.svg",
    tags: ["Next.js", "PostgreSQL", "AWS"],
    color: "#8B5CF6",
  },
  {
    slug: "insurewise",
    title: "InsureWise",
    subtitle: "Claims Intake Automation",
    industry: "InsurTech",
    year: "2024",
    category: "Enterprise",
    description:
      "Claims intake automation with document capture, triage, and adjuster workflows.",
    problem: "Manual intake caused long cycle times and inconsistent triage decisions.",
    approach: "We built guided intake, automated document checks, and routed cases with policy rules.",
    solution: "A claims intake platform with queues, validations, and reporting.",
    duration: "13 weeks",
    services: ["Workflow design", "Engineering", "Integrations"],
    deliverables: ["Intake UI", "Case queues", "Reporting"],
    features: ["Doc capture", "Validation rules", "Routing"],
    results: [
      { metric: "-33%", label: "Cycle time" },
      { metric: "+17%", label: "First-pass accuracy" },
      { metric: "-40%", label: "Manual review" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "↓ 33% cycle time",
    image: "/images/work/datastream.svg",
    tags: ["Next.js", "Node.js", "PostgreSQL"],
    color: "#10B981",
  },
  {
    slug: "marketlift",
    title: "MarketLift",
    subtitle: "Campaign Analytics + Attribution",
    industry: "MarTech",
    year: "2023",
    category: "AI/ML",
    description:
      "Campaign analytics with multi-touch attribution and automated insights.",
    problem: "Teams lacked consistent attribution and spent time stitching reports across tools.",
    approach: "We unified event tracking, built attribution models, and shipped insight automation.",
    solution: "An analytics suite with attribution, dashboards, and insight alerts.",
    duration: "10 weeks",
    services: ["Data engineering", "ML modeling", "Dashboards"],
    deliverables: ["Attribution", "Dashboards", "Alerts"],
    features: ["Multi-touch models", "Cohorts", "Alerting"],
    results: [
      { metric: "+18%", label: "ROAS" },
      { metric: "-55%", label: "Reporting time" },
      { metric: "<1s", label: "Dash p95" },
      { metric: "+2.3x", label: "Experiment velocity" },
    ],
    metric: "↑ 18% ROAS",
    image: "/images/work/orbita.svg",
    tags: ["Python", "dbt", "BigQuery", "React"],
    color: "#06B6D4",
  },
  {
    slug: "mealmate",
    title: "MealMate",
    subtitle: "Food Ordering + Loyalty",
    industry: "FoodTech",
    year: "2025",
    category: "Mobile",
    description:
      "A mobile ordering experience with loyalty, offers, and store-level operations.",
    problem: "Mobile ordering was slow and loyalty rules were inconsistent across stores.",
    approach: "We optimized ordering flows and rebuilt loyalty rules with clear admin tooling.",
    solution: "A mobile ordering app with loyalty, offers, and store operations dashboards.",
    duration: "8 weeks",
    services: ["Mobile app", "Backend", "UX"],
    deliverables: ["Ordering app", "Loyalty", "Store console"],
    features: ["Saved orders", "Offers", "Loyalty tiers"],
    results: [
      { metric: "+27%", label: "Repeat orders" },
      { metric: "-24%", label: "Checkout time" },
      { metric: "4.7★", label: "Rating" },
      { metric: "+16%", label: "AOV" },
    ],
    metric: "↑ 27% repeat orders",
    image: "/images/work/orbita.svg",
    tags: ["React Native", "Node.js", "Redis"],
    color: "#06B6D4",
  },
  {
    slug: "buildops",
    title: "BuildOps",
    subtitle: "Manufacturing Workflows",
    industry: "Manufacturing",
    year: "2024",
    category: "Enterprise",
    description:
      "Shop-floor workflows, quality checks, and production reporting for multi-line manufacturing.",
    problem: "Quality checks were manual, leading to delays and inconsistent traceability.",
    approach: "We digitized QC flows, built traceability, and integrated with existing ERP exports.",
    solution: "A manufacturing workflow suite with QC, traceability, and live reporting.",
    duration: "15 weeks",
    services: ["Workflow engineering", "Integrations", "QA"],
    deliverables: ["QC module", "Traceability", "Reporting"],
    features: ["Batch tracking", "Defect logging", "Approvals"],
    results: [
      { metric: "-21%", label: "Defects" },
      { metric: "+14%", label: "Throughput" },
      { metric: "-46%", label: "Paperwork" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "↓ 21% defects",
    image: "/images/work/datastream.svg",
    tags: ["Next.js", ".NET", "SQL Server", "Azure"],
    color: "#10B981",
  },
  {
    slug: "mediavault",
    title: "MediaVault",
    subtitle: "Content Archive & Search",
    industry: "Media",
    year: "2023",
    category: "Web",
    description:
      "A content archive with fast search, permissions, and automated metadata extraction.",
    problem: "Teams could not find assets quickly and permissioning was inconsistent.",
    approach: "We built structured metadata, added search, and designed clear permission models.",
    solution: "A media archive with search, previews, and controlled sharing.",
    duration: "6 weeks",
    services: ["Web app", "Search", "Integrations"],
    deliverables: ["Search UI", "Metadata", "Sharing"],
    features: ["Full-text search", "Previews", "Share links"],
    results: [
      { metric: "-68%", label: "Time-to-find" },
      { metric: "+2.9x", label: "Asset reuse" },
      { metric: "1.4s", label: "Search p95" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "↓ 68% time-to-find",
    image: "/images/work/finvest.svg",
    tags: ["Next.js", "PostgreSQL", "S3"],
    color: "#8B5CF6",
  },
  {
    slug: "govconnect",
    title: "GovConnect",
    subtitle: "Citizen Service Portal",
    industry: "GovTech",
    year: "2024",
    category: "Enterprise",
    description:
      "A portal for citizen requests, case tracking, and internal routing with accessibility-first UX.",
    problem: "Requests were handled via email with limited tracking and poor accessibility.",
    approach: "We designed accessible flows, built case routing, and introduced SLAs + reporting.",
    solution: "A citizen portal with case tracking, routing, and audit-ready reporting.",
    duration: "14 weeks",
    services: ["Accessibility", "Platform", "Security"],
    deliverables: ["Portal", "Internal console", "Reporting"],
    features: ["Case tracking", "SLA alerts", "RBAC"],
    results: [
      { metric: "WCAG", label: "AA compliance" },
      { metric: "-47%", label: "Processing time" },
      { metric: "+33%", label: "Self-serve usage" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "WCAG AA compliant",
    image: "/images/work/datastream.svg",
    tags: ["Next.js", "Node.js", "PostgreSQL"],
    color: "#10B981",
  },
  {
    slug: "cyberwatch",
    title: "CyberWatch",
    subtitle: "Security Posture Dashboard",
    industry: "Cybersecurity",
    year: "2025",
    category: "SaaS",
    description:
      "A security posture dashboard aggregating findings, risk scoring, and remediation tracking.",
    problem: "Security findings were scattered across tools and remediation progress lacked visibility.",
    approach: "We unified sources, created a risk model, and built remediation workflows.",
    solution: "A posture management SaaS with scoring, tasks, and stakeholder reporting.",
    duration: "12 weeks",
    services: ["Platform", "Integrations", "Security UX"],
    deliverables: ["Risk model", "Dashboards", "Workflows"],
    features: ["Risk scoring", "Task tracking", "Exports"],
    results: [
      { metric: "-39%", label: "Time-to-remediate" },
      { metric: "+2.1x", label: "Issue throughput" },
      { metric: "99.9%", label: "Uptime" },
      { metric: "<1s", label: "Dash p95" },
    ],
    metric: "↓ 39% time-to-remediate",
    image: "/images/work/finvest.svg",
    tags: ["Next.js", "Go", "PostgreSQL"],
    color: "#8B5CF6",
  },
  {
    slug: "sportpulse",
    title: "SportPulse",
    subtitle: "Fan Engagement App",
    industry: "Sports",
    year: "2023",
    category: "Mobile",
    description:
      "A fan engagement app featuring live polls, rewards, and event check-ins.",
    problem: "Engagement dropped between events and rewards were hard to manage.",
    approach: "We built real-time interactions, simplified rewards, and added event ops tooling.",
    solution: "A mobile engagement app with polls, rewards, and event check-ins.",
    duration: "7 weeks",
    services: ["Mobile", "Realtime", "UX"],
    deliverables: ["Fan app", "Rewards", "Ops console"],
    features: ["Live polls", "Rewards", "Check-ins"],
    results: [
      { metric: "+46%", label: "Monthly active" },
      { metric: "+2.8x", label: "Session time" },
      { metric: "4.6★", label: "Rating" },
      { metric: "-22%", label: "Ops effort" },
    ],
    metric: "↑ 46% MAU",
    image: "/images/work/orbita.svg",
    tags: ["React Native", "Firebase", "Node.js"],
    color: "#06B6D4",
  },
  {
    slug: "legalink",
    title: "LegaliNK",
    subtitle: "Contract Review Workflow",
    industry: "LegalTech",
    year: "2025",
    category: "SaaS",
    description:
      "A contract review workflow with templates, approvals, and searchable clause library.",
    problem: "Contract review cycles were slow and clause reuse was inconsistent.",
    approach: "We standardized templates, built approvals, and created a clause library with search.",
    solution: "A contract workflow SaaS with approvals, templates, and clause intelligence.",
    duration: "9 weeks",
    services: ["Workflow", "Web app", "Search"],
    deliverables: ["Templates", "Approvals", "Clause library"],
    features: ["Clause search", "Approvals", "Versioning"],
    results: [
      { metric: "-34%", label: "Review time" },
      { metric: "+2.2x", label: "Template reuse" },
      { metric: "99.9%", label: "Uptime" },
      { metric: "1.8s", label: "Search p95" },
    ],
    metric: "↓ 34% review time",
    image: "/images/work/finvest.svg",
    tags: ["Next.js", "PostgreSQL", "Elastic"],
    color: "#8B5CF6",
  },
  {
    slug: "rely-ai-support",
    title: "Rely Support",
    subtitle: "AI Assisted Helpdesk",
    industry: "Customer Support",
    year: "2024",
    category: "AI/ML",
    description:
      "AI-assisted helpdesk with suggested replies, knowledge base search, and analytics.",
    problem: "Response times were rising and agents struggled to find accurate KB answers quickly.",
    approach: "We improved KB structure, added semantic search, and built AI suggestions with review.",
    solution: "A helpdesk with AI suggestions, KB search, and QA guardrails.",
    duration: "6 weeks",
    services: ["LLM integration", "UI", "Analytics"],
    deliverables: ["Agent console", "KB search", "Insights"],
    features: ["Suggested replies", "Semantic search", "Auto-tagging"],
    results: [
      { metric: "-29%", label: "First response" },
      { metric: "+17%", label: "CSAT" },
      { metric: "-38%", label: "Handle time" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "↓ 38% handle time",
    image: "/images/work/orbita.svg",
    tags: ["Next.js", "OpenAI", "PostgreSQL"],
    color: "#06B6D4",
  },
  {
    slug: "vaultledger",
    title: "VaultLedger",
    subtitle: "Invoice + Accounting Automation",
    industry: "Finance",
    year: "2023",
    category: "Enterprise",
    description:
      "Invoice automation with approvals, reconciliations, and role-based workflows.",
    problem: "Invoices were processed manually with little visibility and frequent reconciliation errors.",
    approach: "We digitized approvals and built reconciliation tooling with audit-ready reporting.",
    solution: "An invoice automation suite with approvals, reconciliations, and reporting.",
    duration: "12 weeks",
    services: ["Workflow", "Integrations", "Reporting"],
    deliverables: ["Approvals", "Reconciliation", "Reports"],
    features: ["Approvals", "RBAC", "Audit logs"],
    results: [
      { metric: "-51%", label: "Processing time" },
      { metric: "-43%", label: "Errors" },
      { metric: "+2.0x", label: "Throughput" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "↓ 51% processing time",
    image: "/images/work/datastream.svg",
    tags: ["Next.js", "Node.js", "PostgreSQL"],
    color: "#10B981",
  },
  {
    slug: "caretrack",
    title: "CareTrack",
    subtitle: "Remote Patient Monitoring",
    industry: "HealthTech",
    year: "2025",
    category: "Mobile",
    description:
      "Remote monitoring app with device sync, alerts, and clinician review workflows.",
    problem: "Clinicians lacked timely signals and patients struggled with device setup.",
    approach: "We simplified onboarding, added alerts, and built clinician review tooling.",
    solution: "A monitoring solution with device sync, alerts, and review workflows.",
    duration: "11 weeks",
    services: ["Mobile", "Integrations", "UX"],
    deliverables: ["Patient app", "Clinician console", "Alerts"],
    features: ["Device sync", "Alerts", "Trends"],
    results: [
      { metric: "+33%", label: "Adherence" },
      { metric: "-25%", label: "Readmissions" },
      { metric: "4.7★", label: "Rating" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "↓ 25% readmissions",
    image: "/images/work/orbita.svg",
    tags: ["React Native", "Python", "GCP"],
    color: "#06B6D4",
  },
  {
    slug: "stackpilot",
    title: "StackPilot",
    subtitle: "Developer Platform Portal",
    industry: "Developer Tools",
    year: "2024",
    category: "Web",
    description:
      "A developer portal for service catalogs, onboarding, and internal docs.",
    problem: "Teams struggled to discover ownership and standardize service onboarding.",
    approach: "We built a service catalog, ownership models, and templates for onboarding.",
    solution: "A portal with service catalog, onboarding workflows, and docs.",
    duration: "6 weeks",
    services: ["Web app", "Design system", "Integrations"],
    deliverables: ["Service catalog", "Onboarding", "Docs"],
    features: ["Ownership", "Templates", "Search"],
    results: [
      { metric: "+2.4x", label: "Onboarding speed" },
      { metric: "-37%", label: "Incidents" },
      { metric: "1.2s", label: "Search p95" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "↑ 2.4x onboarding speed",
    image: "/images/work/finvest.svg",
    tags: ["Next.js", "MDX", "PostgreSQL"],
    color: "#8B5CF6",
  },
  {
    slug: "bazarkart",
    title: "Bazarkart",
    subtitle: "E-commerce Mobile App",
    industry: "E-commerce",
    year: "2024",
    category: "Mobile",
    description: "Feature-rich e-commerce mobile app with secure transactions, product catalog, and real-time order tracking.",
    problem: "Sellers needed a mobile-first marketplace with secure payments and real-time inventory.",
    approach: "We designed a clean mobile UX, integrated payment gateways, and built a scalable product catalog backend.",
    solution: "A cross-platform e-commerce app with product discovery, cart, secure checkout, and order tracking.",
    duration: "10 weeks",
    services: ["Mobile engineering", "UI/UX", "Backend", "Payments"],
    deliverables: ["iOS & Android app", "Seller dashboard", "Payment integration", "Order tracking"],
    features: ["Product catalog", "Secure checkout", "Order tracking", "Push notifications"],
    results: [
      { metric: "10K+", label: "Downloads" },
      { metric: "4.7★", label: "App rating" },
      { metric: "99.9%", label: "Payment success" },
      { metric: "<2s", label: "Page load" },
    ],
    metric: "4.7★ App Store rating",
    image: "/images/work/orbita.svg",
    tags: ["Flutter", "Node.js", "PostgreSQL", "Razorpay"],
    color: "#8B5CF6",
  },
  {
    slug: "bibbox-b2b",
    title: "Bibbox B2B",
    subtitle: "Wholesale E-commerce Platform",
    industry: "B2B Commerce",
    year: "2024",
    category: "Web",
    description: "B2B wholesale platform connecting suppliers with bulk buyers — catalog, negotiation, and order management in one place.",
    problem: "Wholesalers relied on phone calls and spreadsheets with no digital order management.",
    approach: "We built a B2B portal with tiered pricing, bulk order flows, and supplier-buyer communication.",
    solution: "A wholesale commerce platform with bulk pricing, RFQ workflows, and order management.",
    duration: "12 weeks",
    services: ["Web app", "B2B workflows", "Backend", "Integrations"],
    deliverables: ["Buyer portal", "Supplier dashboard", "Order management", "Negotiation flows"],
    features: ["Bulk pricing tiers", "RFQ system", "Invoice generation", "Multi-location inventory"],
    results: [
      { metric: "+65%", label: "Order efficiency" },
      { metric: "-70%", label: "Manual processing" },
      { metric: "500+", label: "Active suppliers" },
      { metric: "99.9%", label: "Uptime" },
    ],
    metric: "+65% order efficiency",
    image: "/images/work/finvest.svg",
    tags: ["Next.js", "Node.js", "PostgreSQL", "AWS"],
    color: "#06B6D4",
  },
  {
    slug: "gym-tym",
    title: "Gym Tym",
    subtitle: "Fitness Platform",
    industry: "Health & Fitness",
    year: "2023",
    category: "Mobile",
    description: "State-of-the-art fitness platform with workout plans, progress tracking, and community features.",
    problem: "Fitness enthusiasts lacked a personalized platform to track progress and access expert-curated plans.",
    approach: "We designed a gamified mobile experience with personalized plans, progress analytics, and social features.",
    solution: "A mobile fitness app with curated workouts, progress tracking, nutrition logging, and community leaderboards.",
    duration: "8 weeks",
    services: ["Mobile engineering", "UX Design", "Backend", "Analytics"],
    deliverables: ["iOS & Android app", "Trainer portal", "Progress dashboard", "Community feed"],
    features: ["Workout plans", "Progress tracking", "Nutrition logging", "Live challenges"],
    results: [
      { metric: "+44%", label: "User retention" },
      { metric: "4.8★", label: "App rating" },
      { metric: "5K+", label: "Active users" },
      { metric: "-30%", label: "Drop-off" },
    ],
    metric: "4.8★ — 5K+ active users",
    image: "/images/work/orbita.svg",
    tags: ["React Native", "Node.js", "MongoDB"],
    color: "#10B981",
  },
];

export const OPEN_POSITIONS = [
  {
    title: "Senior Full-Stack Engineer",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    slug: "senior-fullstack-engineer",
    description:
      "Join our core engineering team building next-generation SaaS products for global clients.",
    requirements: [
      "5+ years with React/Next.js and Node.js",
      "Strong TypeScript skills",
      "Experience with cloud infrastructure (AWS/GCP)",
      "Passion for clean, tested, maintainable code",
    ],
  },
  {
    title: "UI/UX Designer",
    department: "Design",
    location: "Remote / Hybrid",
    type: "Full-time",
    slug: "ui-ux-designer",
    description:
      "Shape the visual language of world-class digital products from concept to pixel-perfect delivery.",
    requirements: [
      "4+ years of product design experience",
      "Mastery of Figma and design systems",
      "Strong portfolio showing end-to-end design thinking",
      "Understanding of frontend implementation",
    ],
  },
  {
    title: "DevOps / Platform Engineer",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    slug: "devops-platform-engineer",
    description:
      "Build and own the infrastructure that powers our clients' products at scale.",
    requirements: [
      "Experience with Kubernetes, Terraform, and CI/CD",
      "AWS or GCP certifications preferred",
      "Strong scripting (Bash, Python, Go)",
      "On-call experience and SRE mindset",
    ],
  },
  {
    title: "AI/ML Engineer",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    slug: "ai-ml-engineer",
    description:
      "Build intelligent systems and LLM-powered features that give our clients a real competitive advantage.",
    requirements: [
      "Strong Python and ML fundamentals",
      "Experience with LLM fine-tuning and RAG pipelines",
      "Familiarity with LangChain, OpenAI APIs",
      "Production ML deployment experience",
    ],
  },
];

export const BLOG_POSTS = [
  {
    slug: "building-real-time-features-nextjs",
    title: "Building Real-Time Features in Next.js with Server-Sent Events",
    excerpt:
      "A deep dive into SSE, React Server Components, and the patterns we use to build snappy real-time UIs without WebSockets.",
    author: "Teklin Engineering",
    authorAvatar: "TE",
    date: "2026-03-15",
    category: "Engineering",
    readTime: "8 min read",
    featured: true,
    image: "/images/blog/real-time-nextjs.jpg",
  },
  {
    slug: "design-systems-at-scale",
    title: "Design Systems at Scale: Lessons from 50+ Product Builds",
    excerpt:
      "The patterns, anti-patterns, and hard-won lessons from building and maintaining design systems across dozens of client products.",
    author: "Teklin Design",
    authorAvatar: "TD",
    date: "2026-02-28",
    category: "Design",
    readTime: "12 min read",
    featured: false,
    image: "/images/blog/design-systems.jpg",
  },
  {
    slug: "llm-integration-production",
    title: "LLM Integration in Production: What Nobody Tells You",
    excerpt:
      "Real-world lessons from deploying LLM-powered features: latency, cost, hallucinations, and how we solved them.",
    author: "Teklin AI Team",
    authorAvatar: "TA",
    date: "2026-02-10",
    category: "AI/ML",
    readTime: "10 min read",
    featured: false,
    image: "/images/blog/llm-production.jpg",
  },
  {
    slug: "zero-downtime-deployments",
    title: "Zero-Downtime Deployments: Our Complete Kubernetes Runbook",
    excerpt:
      "Blue-green, canary, rolling — our complete deployment strategy for keeping client services at 99.9% uptime.",
    author: "Teklin DevOps",
    authorAvatar: "DO",
    date: "2026-01-20",
    category: "DevOps",
    readTime: "15 min read",
    featured: false,
    image: "/images/blog/k8s-deployments.jpg",
  },
];
